### ISSUE TITLE
card links and msg properties

### ISSUE THREAD

**Issue by bilal68** [ifedoroff/msg-parser-js#10]
@ifedoroff Sorry for late reply.I have add the zip for  the examople file. after unzipping if you open the file in a simple text editor and search for url you will see following type of properties which I want to read. which resides in this stream "**__substg1.0_8028001F**".  Kindly help me out ,highly appericiated.

`""url\\\\\\\":\\\\\\\"https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fstatics.retailservices.teams.cdn.office.net%2fui%2fstatic%2fpraise%2fring4%2fall%2fassets%2fbadges%2fen-GB%2fOptimismBadge.b081168fc2.png\\\\\\\",\\\\\\\"height\\\\\\\":\\\\\\\"auto\\\\\\\",\\\\\\\"type\\\\\\\":\\\\\\\"Image\\\\\\\"}],\\\\\\\"type\\\\\\\":\\\\\\\"Column\\\\\\\"},{\\\\\\\"width\\\\\\\":\\\\\\\"6\\\\\\\",\\\\\\\"items\\\\\\\":[{\\\\\\\"isSubtle\\\\\\\":true,\\\\\\\"size\\\\\\\":\\\\\\\"small\\\\\\\",\\\\\\\"text\\\\\\\":\\\\\\\"Mark Anderson sent praise to\\\\\\\",\\\\\\\"wrap\\\\\\\":true,\\\\\\\"type\\\\\\\":\\\\\\\"TextBlock\\\\\\\"},{\\\\\\\"size\\\\\\\":\\\\\\\"medium\\\\\\\",\\\\\\\"text\\\\\\\":\\\\\\\"Chris Angelides\\\\\\\",\\\\\\\"weight\\\\\\\":\\\\\\\"bolder\\\\\\\",\\\\\\\"wrap\\\\\\\":true,\\\\\\\"spacing\\\\\\\":\\\\\\\"small\\\\\\\",\\\\\\\"type\\\\\\\":\\\\\\\"TextBlock\\\\\\\"},{\\\\\\\"text\\\\\\\":\\\\\\\"I like your optimism\\\\\\\",\\\\\\\"wrap\\\\\\\":true,\\\\\\\"spacing\\\\\\\":\\\\\\\"small\\\\\\\",\\\\\\\"type\\\\\\\":\\\\\\\"TextBlock\\\\\\\"}],\\\\\\\"spacing\\\\\\\":\\\\\\\"medium\\\\\\\",\\\\\\\"type\\\\\\\":\\\\\\\"Column\\\\\\\"}],\\\\\\\"spacing\\\\\\\":\\\\\\\"large\\\\\\\",\\\\\\\"separator\\\\\\\":true,\\\\\\\"type\\\\\\\":\\\\\\\"ColumnSet\\\\\\\"}],\\\\\\\"$schema\\\\\\\":\\\\\\\"https://adaptivecards.io/schemas/adaptive-card.json\\\\\\\",\\\\\\\"version\\\\\\\":\\\\\\\"1.0\\\\\\\"},\\\\\\\"contentType\\\\\\\":\\\\\\\"application/vnd.microsoft.card.adaptive\\\\\\\"}]\\\",\\\"ams_references\\\":[]}\",\"threadId\":\"19:b2ea78a2ba9740c7a57678dabbf22d88@thread.tacv2\",\"threadType\":\"space\",\"threadSubType\":\"None\",\"groupId\":\"19:b2ea78a2ba9740c7a57678dabbf22d88@thread.tacv2\",\"aadGroupId\":\"c3423bb4-8920-4999-b9ea-a8706259d6fe\",\"messageType\":\"RichText\",\"messageSubtype\":\"Html\",\"type\":\"Message\",\"imdisplayname\":\"Mark Anderson\",\"workloadItemUrl\":\"https://teams.microsoft.com\",\"workloadNotificationContext\":\"{\\\"SenderId\\\":\\\"e54b76f57cda44fc9f431e1abae9ca25\\\",\\\"AadGroupId\\\":\\\"c3423bb4-8920-4999-b9ea-a8706259d6fe\\\",\\\"ThreadId\\\":\\\"19:b2ea78a2ba9740c7a57678dabbf22d88@thread.tacv2\\\",\\\"MessageId\\\":1589128706031,\\\"ParentMessageId\\\":1589128706031,\\\"TenantId\\\":\\\"47dfd9d1-b58f-4570-92f5-9d135b90464a\\\",\\\"ThreadType\\\":\\\"space\\\",\\\"CorrelationVector\\\":\\\"NqbSyLG5YUK+FXvMnMz1Zg.1.1.3.1.9437202.2.0\\\"}\",\"senderLocale\":\"en-US\",\"toExternal\":false,\"skipDlpClassification\":false}","SkypeItemId":"d23a7d63e4d6162d67d17dbae8b8d73a27bf1229c5f1a15300923e8f737bcf93","SkypeItemId@is.Queryable":true,"CreatedDateTime":"2020-05-10T16:38:26.031Z","CreatedDateTime@is.Queryable":true,"ThreadId":"19:b2ea78a2ba9740c7a57678dabbf22d88@thread.tacv2","ThreadId@is.Queryable":true,"ThreadType":"space","ThreadType@is.Queryable":true,"SkypeGroupId":"19:b2ea78a2ba9740c7a57678dabbf22d88@thread.tacv2","SkypeGroupId@is.Queryable":true,"MessageType":"RichText","MessageType@is.Queryable":true,"FromSkypeInternalId":"8:orgid:e54b76f5-7cda-44fc-9f43-1e1abae9ca25","FromSkypeInternalId@is.Queryable":true,"TeamName":"Chat Testing","TeamName@is.Queryable":true,"Topic":"Chat Testing","Topic@is.Queryable":true,"ParentMessageId":"1589128706031","ParentMessageId@is.Queryable":true,"#type.SkypeItemId":"String","#type.CreatedDateTime":"DateTime","#type.ThreadId":"String","#type.ThreadType":"String","#type.SkypeGroupId":"String","#type.MessageType":"String","#type.FromSkypeInternalId":"String","#type.TeamName":"String","#type.Topic":"String","#type.ParentMessageId":"String"}"AadGroupId\":\"c3423bb4-8920-4999-b9ea-a8706259d6fe\",\"ThreadId\":\"19:b2ea78a2ba9740c7a57678dabbf22d88@thread.tacv2\",\"MessageId\":1589128706031,\"ParentMessageId\":1589128706031,\"TenantId\":\"47dfd9d1-b58f-4570-92f5-9d135b90464a\",\"ThreadType\":\"space\",\"CorrelationVector\":\"NqbSyLG5YUK+FXvMnMz1Zg.1.1.3.1.9437202.2.0\"}","Context@is.Queryable":true,"LinkId":"1589128706031","LinkId@is.Queryable":true,"#type.Context":"String","#type.LinkId":"String"}{"Locale":"en-US","Locale@is.Que__substg1.0_802A001F*_a__substg1.0_802B001F*__substg1.0_802C001F*^__substg1.0_802D001F*ryable":true,"#type.Locale":"String"}{"SkipClassification":false,"SkipClassification@is.Queryable":true,"WorkloadItemUrl":"https://teams.microsoft.com","WorkloadItemUrl@is.Queryable":true,"#type.SkipClassification":"Bool","#type.WorkloadItemUrl":"String"}["`
[Item (1).zip](https://github.com/ifedoroff/msg-parser-js/files/6989860/Item.1.zip)\

thanks

**Comment by bilal68** [comment]
@ifedoroff any luck with the example i provided?

**Comment by ifedoroff** [comment]
Hi @bilal68 . I see that these properties are located under 8027001F rather than 8028001F. Do you need to read this property **8027001F** from the email?

**Comment by bilal68** [comment]
yes...i want to read 8027001F this. the ItemData object.

**Comment by ifedoroff** [comment]
You can read it using the following line of code. I'm not sure how to parse it properly however.
`msg.getProperty(new PropertyTag(0x8027, new PtypString()))`

**Comment by ifedoroff** [comment]
If you decode the property value with certain "json" decoder you will find the card links under 
`decodedValue.ItemData.properties.cards`

**Comment by faransajid** [comment]
Hi @ifedoroff , Thank you, this solves the problem partially because this **itemdata** object varies under multiple addresses (80xx001F), xx being the variable value here. 
Is there any way to list the streams as follow so that I could list all the streams and match the desired ones:

`('__substg1.0_10130102', '__substg1.0_0042001F', '__substg1.0_0065001F', '__substg1.0_0064001F', '__substg1.0_00410102', '__substg1.0_5D02001F', '__substg1.0_5FE5001F', '__substg1.0_0E4E0102', '__substg1.0_0C1A001F', '__substg1.0_0C1F001F', '__substg1.0_0C1E001F', '__substg1.0_0C190102', '__substg1.0_5D01001F', '__substg1.0_0E4D0102', '__substg1.0_0037001F', '__substg1.0_0E1D001F', ...`

**Comment by ifedoroff** [comment]
HI @faransajid, you can use the below code to traverse all properties of an MSG file and print their values:

` msg.propertiesStream().properties()
            .forEach(propertyInfo => console.log(msg.getProperty(propertyInfo.propertyTag())));`

Kindly let me know if I didn't get you right.
