### ISSUE TITLE
Issue parsing with PtypString8 class

### ISSUE THREAD

**Issue by Akhouad** [ifedoroff/msg-parser-js#6]
## Bug Description
Msg files with ID: `0x0037001E` cannot be parsed.
There is indeed the file [PtypString8.ts](https://github.com/ifedoroff/msg-parser-js/blob/aa3bf7557f235b83ea92ed3d91644396203a9837/src/property/property_type/PtypString8.ts) which is responsible for this format (as mentioned in [PropertyTypes.ts:48](https://github.com/ifedoroff/msg-parser-js/blob/aa3bf7557f235b83ea92ed3d91644396203a9837/src/property/property_type/PropertyTypes.ts#L48)), but it contains the wrong ID

### Constructor issue
Replace constructor's parameters to `super(0x001E, "PtypString8")`
https://github.com/ifedoroff/msg-parser-js/blob/aa3bf7557f235b83ea92ed3d91644396203a9837/src/property/property_type/PtypString8.ts#L10

### String comparison issue 
Remove `toUpperCase()` for `getDirectoryEntryName()` method, which caused a bug comparing strings (it is correct in `PtypString.ts` though)
https://github.com/ifedoroff/msg-parser-js/blob/aa3bf7557f235b83ea92ed3d91644396203a9837/src/property/property_type/PtypString8.ts#L19

**Comment by ifedoroff** [comment]
@Akhouad Can you please provide an example of the email for testing purposes?

**Comment by bilal68** [comment]
i want to parse ,msg file included all types of data attachments, embeded images,cards ands gifs. Currently I am using this package
ykarpovich/msg.reader....it gives me array buffer of embeded images and when I change this to base64 the images wont render properly.. what I want to know is that is this plugin parse all the info like body,htmlBody and all the other stuff in the .msg file...if yes how can I use it or do you have docs link to follow then kindly share @ifedoroff

**Comment by ifedoroff** [comment]
@bilal68 Hi Bilal, can you please create a separate issue for this and attach example of an email that can be used for testing?

**Comment by bilal68** [comment]
@ifedoroff  how did you get the recipients list? its showing undefined. How I can get the recipirnt data and all the msg related properties ?

**Comment by Akhouad** [comment]
Hello @ifedoroff 
thank you for the response and the fix, I still think there's a need to to remove .toUppercase (my last paragraph in the issue)

e.g: 
left side: "abc_0x123".toupper -> "ABC_0X123"
right side: "abc_" + "0x123".toupper -> "abc_0X123"

**Comment by ifedoroff** [comment]
Hi @Akhouad Can you please check try out the latest version from **master** branch and see if it works now for your scenario? It has also been published as version 1.0.10 to **npm**.
