### ISSUE TITLE
Unable to extract the card links, parent id, & reactions from the msg file

### ISSUE THREAD

**Issue by faransajid** [ifedoroff/msg-parser-js#8]
I am unable to extract the card links, parent id, & reactions from the msg file. Do we have support for those in this plugin? 
If yes, Could you please let me know how we can do that?

Is there any documentation to use this plugin? Thank you.

**Comment by bilal68** [comment]
@ifedoroff I want read a stream "__substg1.0_8028001F" it contain ItemData object I , but I cant seems to work in this plugin. Can you have any workarounf so we can read the custom stream values and map them in the object as others.
Thanks

**Comment by ifedoroff** [comment]
@faransajid @bilal68 Can you please provide examples of the email(s) for testing purposes? I will take a look and let you know if I can add a support for this.

**Comment by bilal68** [comment]
@ifedoroff I have oppend a new issue. kindly have a look and let meknow if you need anything else to understand the issue.thanks

**Comment by faransajid** [comment]
Thank you for your response @ifedoroff .
We are parsing Microsoft teams exported msg file. I am able to read the msg body html as follows:
```
let buf = Buffer.from(msg.getProperty(PidTagHtml));
console.log(new TextDecoder("utf-8").decode(buf));
```
Apparently, there's another ItemData object in msg file which has other information like cards, emotions, msg important flag.
I am unable to extract that, please let me know if that would be possible. (msg file attached
[Item (1).zip](https://github.com/ifedoroff/msg-parser-js/files/6990670/Item.1.zip)
)

**Comment by ifedoroff** [comment]
@faransajid Kindly check this issue and let me know if it duplicates this one for you:
https://github.com/ifedoroff/msg-parser-js/issues/10
